name: timesync360
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^5.0.0-release-candidate-5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  flutter_native_splash: ^2.3.6
  internet_connection_checker: ^1.0.0+1
  lottie: ^2.7.0
  flex_color_scheme: ^7.3.1
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  dio: ^5.3.4
  logger: ^2.0.2+1
  jwt_decoder: ^2.0.1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  device_info_plus: ^9.1.1
  intl: ^0.18.1
  cached_network_image: ^3.3.0
  loading_animation_widget: ^1.2.0+4
  geolocator: ^10.1.0
  fl_chart: ^0.65.0
  dropdown_button2: ^2.3.9
  file_picker: ^6.1.1
  percent_indicator: ^4.2.3
  flex_color_picker: ^3.3.0
  flutter_zoom_drawer: ^3.1.1
  ntp: ^2.0.0
  month_picker_dialog: ^2.4.0
  table_calendar: ^3.0.9
  http_parser: ^4.0.2
  mime: ^1.0.4
  permission_handler: ^11.2.0
  firebase_core: ^2.25.0
  firebase_crashlytics: ^3.4.12
  firebase_analytics: ^10.8.3
  flutter_typeahead: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/svgs/
    - assets/images/
    - assets/images/profile/
    - assets/images/position/
    - assets/images/organization/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-Bold.ttf
        - asset: assets/font/Inter-Medium.ttf
        - asset: assets/font/Inter-Regular.ttf
        - asset: assets/font/Inter-SemiBold.ttf

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
